spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_db
    username: root
    password: Admin123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog-master.xml

hibernate:
  cache:
    use_second_level_cache: true
    region:
      factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory